In [31]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")
print(df_train.shape, df_test.shape)

(300000, 32) (200000, 31)

In [32]:
df_test.loc[:, "target"] = -1
df_whole = pd.concat([df_train, df_test], ignore_index=True)
df_whole

,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,...,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,target
0,0,A,I,A,B,B,BI,A,S,Q,...,0.759439,0.795549,0.681917,0.621672,0.592184,0.791921,0.815254,0.965006,0.665915,0
1,1,A,I,A,A,E,BI,K,W,AD,...,0.386385,0.541366,0.388982,0.357778,0.600044,0.408701,0.399353,0.927406,0.493729,0
2,2,A,K,A,A,E,BI,A,E,BM,...,0.343255,0.616352,0.793687,0.552877,0.352113,0.388835,0.412303,0.292696,0.549452,0
3,3,A,K,A,C,E,BI,A,Y,AD,...,0.831147,0.807807,0.800032,0.619147,0.221789,0.897617,0.633669,0.760318,0.934242,0
4,4,A,I,G,B,E,BI,C,G,Q,...,0.338818,0.277308,0.610578,0.128291,0.578764,0.279167,0.351103,0.357084,0.328960,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499983,A,N,A,D,F,BI,A,AF,AX,...,0.351946,0.327670,0.205547,0.679195,0.485967,0.319130,0.520681,0.519545,0.427119,-1
499996,499984,B,I,A,B,E,BI,A,AS,S,...,0.628843,0.677765,0.624935,0.555306,0.242424,0.700829,0.531728,0.528427,0.922645,-1
499997,499987,A,L,D,A,H,BI,A,AN,J,...,0.803348,0.324762,0.665624,0.488447,0.853213,0.578641,0.811941,0.537106,0.531758,-1
499998,499994,A,K,A,C,F,BI,A,R,BM,...,0.820635,0.561449,0.797434,0.555089,0.746532,0.369986,0.438712,0.715524,0.381978,-1
499999,499998,A,K,A,A,E,BI,C,AO,BM,...,0.270483,0.581868,0.218993,0.553284,0.565213,0.378355,0.547927,0.273595,0.448016,-1

In [33]:
features = [f for f in df_train.columns if f not in ["id", "target"]]
cat_features = [f for f in features if f.startswith("cat") == True]
cont_features = [f for f in features if f.startswith("cat") == False]
print(features, cat_features, cont_features)

['cat0', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15', 'cat16', 'cat17', 'cat18', 'cont0', 'cont1', 'cont2', 'cont3', 'cont4', 'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10'] ['cat0', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15', 'cat16', 'cat17', 'cat18'] ['cont0', 'cont1', 'cont2', 'cont3', 'cont4', 'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10']

In [3]:
# import itertools
# def feature_engineering(df, cat_cols):
#     """
#     This function is used for feature engineering
#     :param df: the pandas dataframe with train/test data
#     :param cat_cols: list of categorical columns
#     :return: dataframe with new features
#     """   
#     # this will create all 2-combinations of values
#     # in this list
#     # for example:
#     # list(itertools.combinations([1,2,3], 2)) will return
#     # [(1, 2), (1, 3), (2, 3)]
#     combi = list(itertools.combinations(cat_cols, 2))
#     for c1, c2 in combi:
#          df.loc[:,c1 + "_" + c2] = df[c1].astype(str) + "_" + df[c2].astype(str)
#     return df

In [12]:
# feature_engineering(df_whole, cat_features)
# df_whole.columns
# rfe_columns = ['cat0_cat5', 'cat0_cat16', 'cat0_cat17', 'cat1_cat4', 'cat1_cat14', 'cat4_cat11', 'cat4_cat12', 'cat4_cat13', 'cat4_cat14', 'cat11_cat13', 'cat11_cat15', 'cat13_cat15', 'cat13_cat16', 'cat14_cat15', 'cat14_cat18', 'cat15_cat18', 'cat16_cat17']
# feature_engineering improved score by 0.0002. not worth it
# rfe_columns didnt help at all

In [34]:
from sklearn import preprocessing

for f in features:
    if f.startswith("cat"):
        le = preprocessing.LabelEncoder()
        df_whole.loc[:, f] = le.fit_transform(df_whole.loc[:, f])

print(df_whole[features[3]])

['cat0', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10', 'cat11', 'cat12', 'cat13', 'cat14', 'cat15', 'cat16', 'cat17', 'cat18', 'cont0', 'cont1', 'cont2', 'cont3', 'cont4', 'cont5', 'cont6', 'cont7', 'cont8', 'cont9', 'cont10'] 30
0         1
1         0
2         0
3         2
4         1
         ..
499995    3
499996    1
499997    0
499998    2
499999    0
Name: cat3, Length: 500000, dtype: int64

In [24]:
def encode(enc, x_train, y_train, x_test):
    x_train_transformed = enc.fit_transform(x_train, y_train)
    x_test_transformed = enc.transform(x_test)
    return x_train_transformed, x_test_transformed

In [35]:
df_train = df_whole.loc[df_whole.loc[:, "target"] != -1, :]
df_test = df_whole.loc[df_whole.loc[:, "target"] == -1, :]
print(df_train.shape, df_test.shape)

(300000, 32) (200000, 32)

In [15]:
df_whole[cat_features] = df_whole[cat_features].astype('category')
df_whole["target"] = df_whole["target"].astype('category')

In [36]:
# do target encoding
from category_encoders import TargetEncoder, WOEEncoder, CountEncoder # TargetEncoder is better on kaggle



te = TargetEncoder(cols=cat_features)
# we = WOEEncoder(cols=cat_features)
# ce = CountEncoder(cols=cat_features)

# xtrain1, xtest1 = encode(te, df_train, df_train.loc[:, "target"], df_test)
# xtrain2, xtest2 = encode(we, df_train.loc[:, cat_features], df_train.loc[:, "target"], df_test.loc[:, cat_features])
# xtrain3, xtest3 = encode(ce, df_train.loc[:, cat_features], df_train.loc[:, "target"], df_test.loc[:, cat_features])

x_train_transformed = te.fit_transform(df_train, df_train.loc[:, "target"])
x_test_transformed = te.transform(df_test)
x_train_tmp = df_train.loc[:, cat_features].join(x_train_transformed, lsuffix="_enc", rsuffix="_mean")
x_test_tmp = df_test.loc[:, cat_features].join(x_test_transformed, lsuffix="_enc", rsuffix="_mean")

# x_train_transformed = xtrain1.join(xtrain2, lsuffix="_enc1", rsuffix="_enc2").join(xtrain3)
# x_test_transformed = xtest1.join(xtest2, lsuffix="_enc1", rsuffix="_enc2").join(xtest3)
# x_train_tmp = df_train.loc[:, cat_features].join(x_train_transformed, lsuffix="", rsuffix="_enc3")
# x_test_tmp = df_test.loc[:, cat_features].join(x_test_transformed, lsuffix="", rsuffix="_enc3")
# print(x_train_transformed.shape, x_test_transformed.shape)
print(x_train_tmp.shape, x_test_tmp.shape)

# target encoding improved by 0.0004 on kaggle
# target encoding > woe

/root/miniconda3/envs/TPS-MAR/lib/python3.9/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

(300000, 51) (200000, 51)

In [38]:
# import xgboost as xgb
# clf =  xgb.XGBClassifier(n_jobs=-1, use_label_encoder=False)

# from sklearn.ensemble import RandomForestClassifier # worse than xbg
# clf = RandomForestClassifier(n_jobs=-1)

from lightgbm import LGBMClassifier # best ... lgbm > xgb > randomforest
cat_features_idx = [i for i in range(len(x_train_tmp.columns)) if "_enc" in x_train_tmp.columns[i]] # have to specify idx for lgbm, not working with columns name weird
print(len(cat_features_idx))
print(x_train_tmp.columns[cat_features_idx[7]])
print(x_train_tmp)
clf = LGBMClassifier(n_jobs=-1, categorical_feature=cat_features_idx)

# ff = [f for f in df_train.columns if f not in ["id", "target"]]
ff = [f for f in x_train_tmp.columns if f not in ["id", "target"]]
print(len(ff))
# clf.fit(df_train.loc[:, ff], df_train.loc[:, "target"])
clf.fit(x_train_tmp.loc[:, ff], x_train_tmp.loc[:, "target"])

19
cat7_enc
        cat0_enc  cat1_enc  cat2_enc  cat3_enc  cat4_enc  cat5_enc  cat6_enc  \
0              0         8         0         1         1        33         0
1              0         8         0         0         4        33         8
2              0        10         0         0         4        33         0
3              0        10         0         2         4        33         0
4              0         8         6         1         4        33         2
...          ...       ...       ...       ...       ...       ...       ...
299995         0        13         5         0         4        45         0
299996         0        10         0         0         6        33         0
299997         0         6        12         0         7        33         2
299998         1         7         0         3         1        33         0
299999         0         5         2         0         4        33         2

        cat7_enc  cat8_enc  cat9_enc  ...     cont2     cont3     cont4  \
0             44        54         0  ...  0.759439  0.795549  0.681917
1             48         3         5  ...  0.386385  0.541366  0.388982
2             30        38         9  ...  0.343255  0.616352  0.793687
3             50         3         5  ...  0.831147  0.807807  0.800032
4             32        54         0  ...  0.338818  0.277308  0.610578
...          ...       ...       ...  ...       ...       ...       ...
299995        19        48         0  ...  0.662428  0.671927  0.390566
299996        36         4         4  ...  0.821657  0.620356  0.384891
299997        37        43         0  ...  0.407037  0.232436  0.832482
299998         1        23         0  ...  0.808045  0.630708  0.346898
299999        22        55         0  ...  0.775451  0.848696  0.819377

           cont5     cont6     cont7     cont8     cont9    cont10  target
0       0.621672  0.592184  0.791921  0.815254  0.965006  0.665915       0
1       0.357778  0.600044  0.408701  0.399353  0.927406  0.493729       0
2       0.552877  0.352113  0.388835  0.412303  0.292696  0.549452       0
3       0.619147  0.221789  0.897617  0.633669  0.760318  0.934242       0
4       0.128291  0.578764  0.279167  0.351103  0.357084  0.328960       1
...          ...       ...       ...       ...       ...       ...     ...
299995  0.145840  0.262767  0.514248  0.519340  0.617436  0.688007       0
299996  0.735879  0.547731  0.726653  0.470575  0.275743  0.638939       0
299997  0.810663  0.596939  0.308821  0.373997  0.518024  0.452144       1
299998  0.735147  0.563488  0.609836  0.680430  0.318453  0.335822       0
299999  0.355467  0.218153  0.968856  0.823655  0.330515  0.972569       0

[300000 rows x 51 columns]
49

/root/miniconda3/envs/TPS-MAR/lib/python3.9/site-packages/lightgbm/basic.py:1075: UserWarning: categorical_feature keyword has been found in `params` and will be ignored.
Please use categorical_feature argument of the Dataset constructor to pass this parameter.
  warnings.warn('{0} keyword has been found in `params` and will be ignored.\n'

LGBMClassifier(categorical_feature=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                    13, 14, 15, 16, 17, 18])

In [16]:
df_test.reset_index()

,index,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,...,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,target
0,300000,5,0,5,0,0,5,33,0,8,...,0.578366,0.723154,0.228037,0.356227,0.551249,0.655693,0.598331,0.359987,0.947489,-1
1,300001,6,0,7,2,0,4,2,7,31,...,0.928885,0.516602,0.600169,0.795224,0.248987,0.654614,0.347944,0.565520,0.388580,-1
2,300002,8,0,13,2,0,5,2,0,8,...,0.424876,0.344729,0.242073,0.270632,0.746740,0.335590,0.341238,0.252289,0.411592,-1
3,300003,9,1,11,2,0,5,33,0,30,...,0.598943,0.561971,0.806347,0.735983,0.538724,0.381566,0.481660,0.348514,0.325723,-1
4,300004,11,0,5,0,1,5,33,0,8,...,0.479572,0.767745,0.252454,0.354810,0.178920,0.763479,0.562491,0.466261,0.585781,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,499995,499983,0,13,0,3,5,33,0,6,...,0.351946,0.327670,0.205547,0.679195,0.485967,0.319130,0.520681,0.519545,0.427119,-1
199996,499996,499984,1,8,0,1,4,33,0,19,...,0.628843,0.677765,0.624935,0.555306,0.242424,0.700829,0.531728,0.528427,0.922645,-1
199997,499997,499987,0,11,3,0,7,33,0,14,...,0.803348,0.324762,0.665624,0.488447,0.853213,0.578641,0.811941,0.537106,0.531758,-1
199998,499998,499994,0,10,0,2,5,33,0,43,...,0.820635,0.561449,0.797434,0.555089,0.746532,0.369986,0.438712,0.715524,0.381978,-1
199999,499999,499998,0,10,0,0,4,33,2,15,...,0.270483,0.581868,0.218993,0.553284,0.565213,0.378355,0.547927,0.273595,0.448016,-1

In [39]:
# df_test.loc[:, "target"] = clf.predict_proba(df_test.loc[:, ff])[:,1]
# df_test.loc[:, ["id", "target"]].to_csv("output.csv", index=False)

x_test_tmp.loc[:, "target"] = clf.predict_proba(x_test_tmp.loc[:, ff])[:,1]
x_test_tmp.loc[:, ["id", "target"]].to_csv("output.csv", index=False)